# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 104b879bc89669626b37d64bfc0fd6062c28610aecf25de06e3cf7f66727e4681e4f61b2d9e0628cab0feb11bd6e1f6a0e715df876752ce93a5ae528afac42ea

test:
  secret_key_base: 60ceba854d50ba226302e445998ccfd43c0c16ab5ad830d40c0cd58a04af2ef34cc322ef6cc637ed7e291fc2ad6ac30418ed96bb485e2ce2914d8b30fcb6a61a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
